### ISSUE TITLE
simhash_imp.py报错： ValueError: could not convert string to float: (0,

### ISSUE THREAD

**Issue by cxzhp** [zyymax/text-similarity#2]
Traceback (most recent call last):
  File "src/simhash_imp.py", line 191, in <module>
    feature_vec = [(int(item.split(':')[0]),float(item.split(':')[1])) for item in feature_vec]
ValueError: could not convert string to float: (0,
1. 打印了下feature_vec 变量， 内容是这样的：

"['0:(0,', '1)', '1:(1,', '1)', '2:(2,', '1)', '3:(15,', '1)', '4:(18,', '1)', '5:(19,', '1)']"
1. 前一步生成的.feat文件，内容是这样的：

$ cat data/temp/all.feat

0:(0, 1) 1:(1, 1) 2:(2, 1) 3:(15, 1) 4:(18, 1) 5:(19, 1)
0:(0, 1) 1:(3, 1) 2:(5, 1) 3:(9, 1) 4:(16, 1) 5:(17, 1)
0:(1, 1) 1:(6, 1) 2:(7, 1) 3:(13, 1) 4:(14, 1) 5:(20, 1)
0:(0, 2) 1:(2, 1) 2:(4, 1) 3:(11, 1) 4:(12, 1)
0:(8, 1) 1:(10, 1) 2:(21, 1)

**Comment by zyymax** [comment]
all.feat文件里，同一个特征项应该是 id:float 的健值对

你的特征文件是用脚本生成的么

2016-08-11 14:21 GMT+08:00 Ping Zhou (Johnny) notifications@github.com:

**Comment by cxzhp** [comment]
是用脚本生成的
1. 执行的命令是：

src/webcontent_filter.sh data/temp/test.content data/temp/test.ori
mv data/temp/test.ori data/temp/all.ori

python src/tokens.py -s data/temp/all.ori data/temp/all.token c data/stopwords.txt

src/DictBuilder.py data/temp/all.token data/temp/word.dict

src/features.py -s data/temp/word.dict data/temp/all.token data/temp/all.feat

python src/simhash_imp.py data/temp/word.dict data/temp/all.feat data/temp/all.fprint
1. 其中：  test.content的内容如下：

temp git:(master) $ cat test.content

"完整的单元测试很少只执行一个测试用例，"
"开发人员通常都需要编写多个测试用例才能"
"对某一软件功能进行比较完整的测试，这些"
"相关的测试用例称为一个测试用例集，在"
"PyUnit中是用TestSuite类来表示的。"
1. 生成的feat文件，内容是这样子的：

temp git:(master)  $ cat all.feat

0:(0, 1) 1:(1, 1) 2:(2, 1) 3:(15, 1) 4:(18, 1) 5:(19, 1)
0:(0, 1) 1:(3, 1) 2:(5, 1) 3:(9, 1) 4:(16, 1) 5:(17, 1)
0:(1, 1) 1:(6, 1) 2:(7, 1) 3:(13, 1) 4:(14, 1) 5:(20, 1)
0:(0, 2) 1:(2, 1) 2:(4, 1) 3:(11, 1) 4:(12, 1)
0:(8, 1) 1:(10, 1) 2:(21, 1)

**Comment by zyymax** [comment]
fix 了，pull下试试

2016-08-12 14:18 GMT+08:00 Ping Zhou (Johnny) notifications@github.com:

**Comment by 307509256** [comment]
(tensorflow) niby:text-similarity niby$ python src/isSimilar.py data/1.ori data/key.ori data/stopwords.txt data/word.dict -c 0.8
Arguments: ['data/1.ori', 'data/key.ori', 'data/stopwords.txt', 'data/word.dict', '-c', '0.8']
Loaded data/1.ori
Loaded data/key.ori
Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/gs/y_x872ks77q7qygnyhbcccmh0000gn/T/jieba.cache
Loading model cost 0.421 seconds.
Prefix dict has been built succesfully.
Loading word dict...
Traceback (most recent call last):
  File "src/isSimilar.py", line 56, in <module>
    doc_feat_2 = fb.compute(doc_token_2)
  File "/Users/niby/Documents/workspace/github/0407/text-similarity/src/features.py", line 20, in compute
    feature[self.word_dict[token]] += 1
KeyError: u'food'

**Comment by zyymax** [comment]
这种 KeyError: u'food' 都是出现了字典中不存在的token

**Comment by Arouniversal** [comment]
Totally: 0 words

processing doc 0
Traceback (most recent call last):
  File "src/simhash_imp.py", line 189, in <module>
    fingerprint = sim_b.sim_hash_nonzero(feature_vec)
  File "src/simhash_imp.py", line 52, in sim_hash_nonzero
    hashval = self.hashval_list[int(idx)]
IndexError: list index out of range
您好，这个？
